@startuml

!theme vibrant

interface DOMParentNode {
  +append(DOMNode | string ...nodes) : void
  +prepend(DOMNode | string ...nodes) : void
}

interface DOMChildNode {

  +after(DOMNode | string ...nodes) : void
  +before(DOMNode | string ...nodes) : void
  +remove() : void
  +replaceWith(DOMNode | string ...$nodes) : void
}

class DOMXPath {

  +readonly document : DOMDocument 
  +registerNodeNamespaces : bool

  +__construct(document :  DOMDocument, registerNodeNS = true : bool)
  +evaluate(expression :  string, contextNode = null : null | DOMNode, registerNodeNS = true : bool) : mixed
  +query(expression :  string, contextNode = null : null | DOMNode, registerNodeNS = true : bool) : mixed
  +registerNamespace(prefix :  string, namespace : string) : bool
  +registerPhpFunctions(string | array | null restrict = null) : void
}
@enduml