@startuml
!theme vibrant
interface DOMParentNode
DOMNode <|-- DOMDocumentFragment

DOMParentNode <|.. DOMDocumentFragment

class DOMDocumentFragment {
  +readonly firstElementChild : null | DOMElement
  +readonly lastElementChild : null | DOMElement
  +readonly childElementCount : int
  +__construct()
  +appendXML(data : string) : bool
}
@enduml
